build: Add workflow for users to self-assign issues by comment
openedx/.github pull request #15
Opened 2022-08-23 22:08 UTC by sarina

2022-08-23 22:10 UTC, sarina commented
@Carlos-Muniz wanna take a look?

note I have this running & tested:

https://github.com/openedx/platform-roadmap/issues/128 as well as https://github.com/sarina/gh-scripting/issues/1 testing that an out-of-org member could use successfully

2022-08-24 18:57 UTC, Carlos-Muniz approved these changes
Hey it looks great. At the bottom of the each of the files there's a notification saying that there isn't a new line at the bottom of each files.

2022-08-24 19:25 UTC, Carlos-Muniz commented on .github/workflows/self-assign-issue.yml
> +          assignees: ${{ github.triggering_actor }}
```suggestion
          assignees: ${{ github.triggering_actor }}

```

2022-08-24 19:25 UTC, Carlos-Muniz commented on workflow-templates/self-assign-issue.yml
> +    uses: openedx/.github/.github/workflows/self-assign-issue.yml@master
```suggestion
    uses: openedx/.github/.github/workflows/self-assign-issue.yml@master

```

2022-08-24 20:10 UTC, nedbat requested changes

2022-08-25 14:18 UTC, nedbat approved these changes

2022-08-25 14:32 UTC, merged