feat: variable changes
openedx/.github pull request #24
Opened 2022-10-04 17:44 UTC by rayzhou-bit

2022-10-04 19:40 UTC, timmc-edx approved these changes
Looks right.

2022-10-05 15:03 UTC, sarina requested changes

2022-10-05 15:03 UTC, sarina commented on .github/workflows/upgrade-python-requirements.yml
> +        run: echo "target_branch=$(if ['$BRANCH' = '']; then echo 'master'; else echo '$BRANCH'; fi)" >> $GITHUB_ENV
Not all repos use `master` as the default branch. You should use the default branch info - I think you can grab that in an action.

2022-10-05 15:05 UTC, sarina commented on .github/workflows/upgrade-python-requirements.yml
> +        run: echo "target_branch=$(if ['$BRANCH' = '']; then echo 'master'; else echo '$BRANCH'; fi)" >> $GITHUB_ENV
quick google suggests `${{ github.event.repository.default_branch }}`

2022-10-05 21:09 UTC, sarina approved these changes

2022-10-17 19:23 UTC, merged